### ISSUE TITLE
Python Error (data related?)

### ISSUE THREAD

**Issue by linkeli742** [taehojo/SWAT#2]
Hi there,

Thank you for providing a tool for us to use! when using I encountered the following error: (I masked the directory to my data)
Is it more like a data issue? What format should the data be in?

Thank you so much for your help! 

--- error code:

Traceback (most recent call last):
  File "<mask>/SWAT/main.py", line 98, in <module>
    main(args.input_file, args.win, args.imputation, args.num_results, args.num_jobs, args.classifier, args.no_plots, args.fast_run, args.api, args.WGS_select, args.WGS_merge, args.name)
  File "<mask>/SWAT/main.py", line 23, in main
    data_imputed = impute_data(data, imputation_method)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<mask>/SWAT/scripts/utils.py", line 18, in impute_data
    return pd.DataFrame(imputer.fit_transform(data), columns=data.columns)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<mask>miniconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<mask>miniconda3/lib/python3.11/site-packages/sklearn/base.py", line 916, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<mask>miniconda3/lib/python3.11/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<mask>miniconda3/lib/python3.11/site-packages/sklearn/impute/_knn.py", line 229, in fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "<mask>miniconda3/lib/python3.11/site-packages/sklearn/base.py", line 605, in _validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<mask>miniconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 795, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: at least one array or dtype is required

**Comment by taehojo** [comment]
Hi, the error seems related to the input data format. 
Ensure your CSV file has column headers, properly marked missing values, and consistent data types. If the issue persists, check the file path and permissions. 
Thanks,

**Comment by linkeli742** [comment]
It's resolved! After studying the utils code I realize it requires a space delimited csv file and it worked out after I adjust for the data format
Side note if you can write that in the readme or in the code about the data format it will be real helpful.
Thank you for the amazing paper and tool!
